<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC28JG5p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC28JG5p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC28JG5p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC28JG5p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC28JG5p\App_KernelDevDebugContainer([
    'container.build_hash' => 'C28JG5p',
    'container.build_id' => '4d5edf7c',
    'container.build_time' => 1580319807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC28JG5p');
