<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKb3IO1h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKb3IO1h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKb3IO1h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKb3IO1h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKb3IO1h\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kb3IO1h',
    'container.build_id' => '7f48a6b1',
    'container.build_time' => 1613586469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKb3IO1h');
