<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9xYgc8Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9xYgc8Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9xYgc8Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9xYgc8Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9xYgc8Y\App_KernelDevDebugContainer([
    'container.build_hash' => '9xYgc8Y',
    'container.build_id' => '04e72015',
    'container.build_time' => 1612377797,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9xYgc8Y');
