<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'product' => [['num1', 'num2'], ['_controller' => 'App\\Controller\\Example1::product'], [], [['variable', '/', '[^/]++', 'num2', true], ['variable', '/', '[^/]++', 'num1', true], ['text', '/product']], [], []],
    'default1' => [['num'], ['num' => 3, '_controller' => 'App\\Controller\\Example1::default1'], [], [['variable', '/', '[^/]++', 'num', true], ['text', '/default1']], [], []],
    'default2' => [['num'], ['num' => '4', '_controller' => 'App\\Controller\\Example1::default2'], [], [['variable', '/', '[^/]++', 'num', true], ['text', '/default2']], [], []],
    'square' => [['num'], ['_controller' => 'App\\Controller\\Example1::square'], [], [['variable', '/', '[^/]++', 'num', true], ['text', '/square']], [], []],
    'testRequest' => [[], ['_controller' => 'App\\Controller\\Example1::testRequest'], [], [['text', '/testRequest']], [], []],
    'session1' => [[], ['_controller' => 'App\\Controller\\Example1::session1'], [], [['text', '/session1']], [], []],
    'session2' => [[], ['_controller' => 'App\\Controller\\Example1::session2'], [], [['text', '/session2']], [], []],
    'hello' => [[], ['_controller' => 'App\\Controller\\OrdersBase::home'], [], [['text', '/hello']], [], []],
    'categories' => [[], ['_controller' => 'App\\Controller\\OrdersBase::categories'], [], [['text', '/categories']], [], []],
    'products' => [['id'], ['_controller' => 'App\\Controller\\OrdersBase::products'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/products']], [], []],
    'cart' => [[], ['_controller' => 'App\\Controller\\OrdersBase::cart'], [], [['text', '/cart']], [], []],
    'add' => [[], ['_controller' => 'App\\Controller\\OrdersBase::add'], [], [['text', '/add']], [], []],
    'remove' => [[], ['_controller' => 'App\\Controller\\OrdersBase::remove'], [], [['text', '/remove']], [], []],
    'processOrder' => [[], ['_controller' => 'App\\Controller\\OrdersBase::processOrder'], [], [['text', '/processOrder']], [], []],
];
